// PORT=5000
// MONGODB_URL=""
// PUBLIC_URL=http://localhost:3000,http://localhost:5173
// JWT_SECRET_KEY=''

// STRIPE_SECRET=""
// STRIPE_PUBLICE = ""
// // #------------------ Firebase Admin -------------------
// FIREBASE_ADMIN_TYPE=""
// FIREBASE_ADMIN_PROJECT_ID=""
// FIREBASE_ADMIN_PRIVATE_KEY_ID=""
// FIREBASE_ADMIN_PRIVATE_KEY=""
// FIREBASE_ADMIN_CLIENT_EMAIL=""
// FIREBASE_ADMIN_CLIENT_ID=""
// FIREBASE_ADMIN_AUTH_URI=""
// FIREBASE_ADMIN_TOKEN_URI=""
// FIREBASE_ADMIN_AUTH_PROVIDER_X509=""
// FIREBASE_ADMIN_CLIENT_X509=""
// FIREBASE_ADMIN_UNIVERSE_DOMAIN=""
// FIRABASE_STORAGE_BUCKET = ""